[tool.cibuildwheel]
build-verbosity = "3"
[build-system]
requires = [
    "numpy",
    "scipy",
    "setuptools>=42",
    "wheel",
    "cmake>=3.16",
    "packaging",
]

build-backend = "setuptools.build_meta"

